---
services:
  aw:
    image: autoware:dev
    build:
      context: ../
      dockerfile: ./humble/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        USERNAME: ${CONTAINER_USER} 
